#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/Users/kchen/miniconda3/envs/bmtk/lib/python3.7/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/Users/kchen/miniconda3/envs/bmtk/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/Users/kchen/Desktop/TA2020A/professional-workshop-3/tutorials/W4_ModelPractice/E-I-Integration/x86_64/.libs/libnrnmech.so" "$@"
